spring:
  artemis:
    user: tacoweb
    password: 13tm31n
  jms:
    template:
      default-destination: tacocloud.order.queue
  application:
    name: taco-cloud
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liEECDiHrq5PIBog
            client-secret: 01ff35485e88a48827638821114006c533ec47eb
          taco-admin-client:
            provider: tacocloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: writeIngredients,deleteIngredients,openid
        provider:
          tacocloud:
            issuer-uri: http://localhost:9000
            authorization-uri: http://localhost:9000/oauth2/authorize
            token-uri: http://localhost:9000/oauth2/token
            jwk-set-uri: http://localhost:9000/oauth2/jwks
            user-info-uri: http://localhost:9000/userinfo
            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  datasource:
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
